# Generated by Django 4.0.4 on 2022-05-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kakao_id', models.BigIntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('profile_image', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('profile_image', models.CharField(max_length=500)),
                ('introduction', models.CharField(max_length=1000)),
                ('carrer', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'creators',
            },
        ),
    ]
