# Generated by Django 4.0.4 on 2022-05-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_status_product_type'),
        ('users', '0005_alter_user_age_alter_user_email_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_myclass', to='products.product'),
        ),
    ]
