# Generated by Django 4.0.4 on 2022-05-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
